"""Unit tests for generation/generator.py."""

import pytest
from unittest.mock import MagicMock, patch

from generation.generator import Generator
from ingestion.chunker import Chunk


@pytest.fixture
def settings():
    s = MagicMock()
        s.anthropic_api_key = "test-key"
            s.generation_model = "claude-3-haiku-20240307"
                s.max_tokens = 512
                    s.temperature = 0.0
                        return s


                        @pytest.fixture
                        def sample_chunks():
                            return [
                                    Chunk(
                                                text="Reciprocal Rank Fusion combines rankings from multiple retrievers.",
                                                            metadata={"source": "docs/architecture.md"},
                                                                        score=0.95,
                                                                                ),
                                                                                        Chunk(
                                                                                                    text="BM25 is a probabilistic sparse retrieval algorithm.",
                                                                                                                metadata={"source": "docs/retrieval.md"},
                                                                                                                            score=0.88,
                                                                                                                                    ),
                                                                                                                                        ]
                                                                                                                                        
                                                                                                                                        
                                                                                                                                        class TestGenerator:
                                                                                                                                            def test_generate_returns_string(self, settings, sample_chunks):
                                                                                                                                                    with patch("generation.generator.anthropic.Anthropic") as mock_cls:
                                                                                                                                                                mock_client = MagicMock()
                                                                                                                                                                            mock_cls.return_value = mock_client
                                                                                                                                                                                        mock_client.messages.create.return_value.content = [
                                                                                                                                                                                                        MagicMock(text="RRF combines rankings.")
                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                                gen = Generator(settings=settings)
                                                                                                                                                                                                                                            answer = gen.generate(query="What is RRF?", chunks=sample_chunks)
                                                                                                                                                                                                                                                        assert isinstance(answer, str)
                                                                                                                                                                                                                                                                    assert len(answer) > 0
                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                        def test_generate_calls_api_once(self, settings, sample_chunks):
                                                                                                                                                                                                                                                                                with patch("generation.generator.anthropic.Anthropic") as mock_cls:
                                                                                                                                                                                                                                                                                            mock_client = MagicMock()
                                                                                                                                                                                                                                                                                                        mock_cls.return_value = mock_client
                                                                                                                                                                                                                                                                                                                    mock_client.messages.create.return_value.content = [
                                                                                                                                                                                                                                                                                                                                    MagicMock(text="Answer.")
                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                            gen = Generator(settings=settings)
                                                                                                                                                                                                                                                                                                                                                                        gen.generate(query="Test?", chunks=sample_chunks)
                                                                                                                                                                                                                                                                                                                                                                                    mock_client.messages.create.assert_called_once()
                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                        def test_generate_empty_chunks(self, settings):
                                                                                                                                                                                                                                                                                                                                                                                                with patch("generation.generator.anthropic.Anthropic") as mock_cls:
                                                                                                                                                                                                                                                                                                                                                                                                            mock_client = MagicMock()
                                                                                                                                                                                                                                                                                                                                                                                                                        mock_cls.return_value = mock_client
                                                                                                                                                                                                                                                                                                                                                                                                                                    mock_client.messages.create.return_value.content = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                    MagicMock(text="I don't know.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gen = Generator(settings=settings)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        answer = gen.generate(query="Unknown?", chunks=[])
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    assert isinstance(answer, str)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def test_generate_uses_configured_model(self, settings, sample_chunks):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                settings.generation_model = "claude-3-opus-20240229"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with patch("generation.generator.anthropic.Anthropic") as mock_cls:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    mock_client = MagicMock()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                mock_cls.return_value = mock_client
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            mock_client.messages.create.return_value.content = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            MagicMock(text="Answer.")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gen = Generator(settings=settings)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                gen.generate(query="Test", chunks=sample_chunks)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            call_kwargs = mock_client.messages.create.call_args
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        model = call_kwargs.kwargs.get("model") or call_kwargs[1].get("model")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    assert model == "claude-3-opus-20240229"
