"""LRU cache for retrieval query results to avoid redundant index lookups."""
from __future__ import annotations

import hashlib
import json
import time
from collections import OrderedDict
from dataclasses import dataclass, field
from threading import Lock
from typing import Any, Dict, List, Optional


@dataclass
class CacheEntry:
    """A single cached retrieval result."""

        results: List[Dict[str, Any]]
            created_at: float = field(default_factory=time.monotonic)
                hits: int = 0

                    def is_expired(self, ttl_seconds: float) -> bool:
                            return (time.monotonic() - self.created_at) > ttl_seconds


                            class QueryCache:
                                """Thread-safe LRU cache for retrieval results.

                                    Args:
                                            max_size: Maximum number of query results to store.
                                                    ttl_seconds: Time-to-live for each entry in seconds.
                                                        """

                                                            def __init__(self, max_size: int = 256, ttl_seconds: float = 300.0) -> None:
                                                                    self._max_size = max_size
                                                                            self._ttl = ttl_seconds
                                                                                    self._cache: OrderedDict[str, CacheEntry] = OrderedDict()
                                                                                            self._lock = Lock()
                                                                                                    self._total_hits = 0
                                                                                                            self._total_misses = 0
                                                                                                            
                                                                                                                # ------------------------------------------------------------------
                                                                                                                    # Public API
                                                                                                                        # ------------------------------------------------------------------
                                                                                                                        
                                                                                                                            def get(self, query: str, filters: Optional[Dict] = None) -> Optional[List[Dict[str, Any]]]:
                                                                                                                                    """Return cached results for *query* or ``None`` on a miss."""
                                                                                                                                            key = self._make_key(query, filters)
                                                                                                                                                    with self._lock:
                                                                                                                                                                entry = self._cache.get(key)
                                                                                                                                                                            if entry is None:
                                                                                                                                                                                            self._total_misses += 1
                                                                                                                                                                                                            return None
                                                                                                                                                                                                                        if entry.is_expired(self._ttl):
                                                                                                                                                                                                                                        del self._cache[key]
                                                                                                                                                                                                                                                        self._total_misses += 1
                                                                                                                                                                                                                                                                        return None
                                                                                                                                                                                                                                                                                    # Move to end (most recently used)
                                                                                                                                                                                                                                                                                                self._cache.move_to_end(key)
                                                                                                                                                                                                                                                                                                            entry.hits += 1
                                                                                                                                                                                                                                                                                                                        self._total_hits += 1
                                                                                                                                                                                                                                                                                                                                    return list(entry.results)
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                        def put(
                                                                                                                                                                                                                                                                                                                                                self,
                                                                                                                                                                                                                                                                                                                                                        query: str,
                                                                                                                                                                                                                                                                                                                                                                results: List[Dict[str, Any]],
                                                                                                                                                                                                                                                                                                                                                                        filters: Optional[Dict] = None,
                                                                                                                                                                                                                                                                                                                                                                            ) -> None:
                                                                                                                                                                                                                                                                                                                                                                                    """Store *results* for *query*."""
                                                                                                                                                                                                                                                                                                                                                                                            key = self._make_key(query, filters)
                                                                                                                                                                                                                                                                                                                                                                                                    with self._lock:
                                                                                                                                                                                                                                                                                                                                                                                                                if key in self._cache:
                                                                                                                                                                                                                                                                                                                                                                                                                                self._cache.move_to_end(key)
                                                                                                                                                                                                                                                                                                                                                                                                                                                self._cache[key] = CacheEntry(results=list(results))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                return
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if len(self._cache) >= self._max_size:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self._cache.popitem(last=False)  # evict LRU
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        self._cache[key] = CacheEntry(results=list(results))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def invalidate(self, query: str, filters: Optional[Dict] = None) -> bool:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    """Remove a specific entry. Returns True if it existed."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            key = self._make_key(query, filters)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    with self._lock:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return self._cache.pop(key, None) is not None
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def clear(self) -> None:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Evict all entries."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    with self._lock:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                self._cache.clear()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    def evict_expired(self) -> int:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            """Remove all expired entries. Returns count removed."""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    removed = 0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            with self._lock:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        expired_keys = [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        k for k, v in self._cache.items() if v.is_expired(self._ttl)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                for k in expired_keys:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                del self._cache[k]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                removed += 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return removed
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # ------------------------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Stats
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # ------------------------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        @property
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def size(self) -> int:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    with self._lock:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return len(self._cache)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @property
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def hit_rate(self) -> float:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                total = self._total_hits + self._total_misses
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return self._total_hits / total if total else 0.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def stats(self) -> Dict[str, Any]:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "size": self.size,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "max_size": self._max_size,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "ttl_seconds": self._ttl,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "total_hits": self._total_hits,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "total_misses": self._total_misses,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "hit_rate": round(self.hit_rate, 4),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # ------------------------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Internals
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # ------------------------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    @staticmethod
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def _make_key(query: str, filters: Optional[Dict]) -> str:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                payload = {"q": query.strip().lower(), "f": filters or {}}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        serialised = json.dumps(payload, sort_keys=True)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return hashlib.sha256(serialised.encode()).hexdigest()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
